profiles:
  local_main_laptop:
    data_root: "D:/datasets/VisA"
    output_root: "./results"

  local_home_laptop:
    data_root: "E:/datasets/VisA"
    output_root: "./results"

  local_desktop:
    data_root: "F:/datasets/VisA"
    output_root: "./results"

  colab_t4:
    data_archive: "/content/drive/MyDrive/VisA_segmentation/VisA.tar"
    data_root: "/content/data/VisA"
    output_root: "/content/drive/MyDrive/VisA_segmentation/visa_results"

  colab_a100:
    data_archive: "/content/drive/MyDrive/VisA_segmentation/VisA.tar"
    data_root: "/content/data/VisA"
    output_root: "/content/drive/MyDrive/VisA_segmentation/visa_results"
